// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PhoneBookApp.ReportService.DataAccess.Context.EntityFramework;

namespace PhoneBookApp.ReportService.DataAccess.Migrations
{
    [DbContext(typeof(PhoneBookAppReportContextEF))]
    [Migration("20210220123011_ChangeEntities")]
    partial class ChangeEntities
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("PhoneBookApp.ReportService.DataAccess.Entities.LocationReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreaatedTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DemandTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<int>("PersonCount")
                        .HasColumnType("integer");

                    b.Property<int>("PhoneCount")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("75331445-ffd9-46b3-912f-3919f0bdd7b3"),
                            CreaatedTime = new DateTime(2021, 2, 20, 15, 30, 9, 478, DateTimeKind.Local).AddTicks(2637),
                            DemandTime = new DateTime(2021, 2, 20, 15, 30, 9, 479, DateTimeKind.Local).AddTicks(8275),
                            Location = "Istanbul",
                            PersonCount = 5,
                            PhoneCount = 10,
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("b04b8919-a184-413e-ad96-666847ccd606"),
                            CreaatedTime = new DateTime(2021, 2, 20, 15, 30, 9, 479, DateTimeKind.Local).AddTicks(9382),
                            DemandTime = new DateTime(2021, 2, 20, 15, 30, 9, 479, DateTimeKind.Local).AddTicks(9404),
                            Location = "Rize",
                            PersonCount = 3,
                            PhoneCount = 20,
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("24e89a68-fb03-49eb-8000-1a2e03bba3ed"),
                            CreaatedTime = new DateTime(2021, 2, 20, 15, 30, 9, 479, DateTimeKind.Local).AddTicks(9431),
                            DemandTime = new DateTime(2021, 2, 20, 15, 30, 9, 479, DateTimeKind.Local).AddTicks(9435),
                            Location = "Antalya",
                            PersonCount = 25,
                            PhoneCount = 50,
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("c5fd9cb3-0ef6-4d34-a8f3-e33fa63a242e"),
                            CreaatedTime = new DateTime(2021, 2, 20, 15, 30, 9, 479, DateTimeKind.Local).AddTicks(9439),
                            DemandTime = new DateTime(2021, 2, 20, 15, 30, 9, 479, DateTimeKind.Local).AddTicks(9441),
                            Location = "Eskişehir",
                            PersonCount = 35,
                            PhoneCount = 150,
                            Status = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
