// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PhoneBookApp.ReportService.DataAccess.Context.EntityFramework;

namespace PhoneBookApp.ReportService.DataAccess.Migrations
{
    [DbContext(typeof(PhoneBookAppReportContextEF))]
    [Migration("20210220222428_UpdateEntityAndPerson")]
    partial class UpdateEntityAndPerson
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("PhoneBookApp.ReportService.DataAccess.Entities.LocationReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreaatedTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DemandTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("PersonCount")
                        .HasColumnType("integer");

                    b.Property<int>("PhoneCount")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Repors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("84e58e81-875d-4809-949c-65cacd40d496"),
                            CreaatedTime = new DateTime(2021, 2, 21, 1, 24, 25, 775, DateTimeKind.Local).AddTicks(6542),
                            DemandTime = new DateTime(2021, 2, 21, 1, 24, 25, 776, DateTimeKind.Local).AddTicks(8080),
                            Location = "Istanbul",
                            PersonCount = 5,
                            PhoneCount = 10,
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("6adac263-d409-4e21-b528-423efc6d8d55"),
                            CreaatedTime = new DateTime(2021, 2, 21, 1, 24, 25, 776, DateTimeKind.Local).AddTicks(8839),
                            DemandTime = new DateTime(2021, 2, 21, 1, 24, 25, 776, DateTimeKind.Local).AddTicks(8854),
                            Location = "Rize",
                            PersonCount = 3,
                            PhoneCount = 20,
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("141310bc-d23d-419e-9bf6-c6b375a72997"),
                            CreaatedTime = new DateTime(2021, 2, 21, 1, 24, 25, 776, DateTimeKind.Local).AddTicks(8870),
                            DemandTime = new DateTime(2021, 2, 21, 1, 24, 25, 776, DateTimeKind.Local).AddTicks(8872),
                            Location = "Antalya",
                            PersonCount = 25,
                            PhoneCount = 50,
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("d204bedd-c9ba-4666-b762-2dda5cb32ade"),
                            CreaatedTime = new DateTime(2021, 2, 21, 1, 24, 25, 776, DateTimeKind.Local).AddTicks(8874),
                            DemandTime = new DateTime(2021, 2, 21, 1, 24, 25, 776, DateTimeKind.Local).AddTicks(8876),
                            Location = "Eskişehir",
                            PersonCount = 35,
                            PhoneCount = 150,
                            Status = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
