// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PhoneBookApp.ReportService.DataAccess.Context.EntityFramework;

namespace PhoneBookApp.ReportService.DataAccess.Migrations
{
    [DbContext(typeof(PhoneBookAppReportContextEF))]
    [Migration("20210220232307_addIsDeletedEntity")]
    partial class addIsDeletedEntity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("PhoneBookApp.ReportService.DataAccess.Entities.LocationReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreaatedTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DemandTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<int>("PersonCount")
                        .HasColumnType("integer");

                    b.Property<int>("PhoneCount")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Reports");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a91a5982-12b0-448a-a1a2-8b1a975f4c66"),
                            CreaatedTime = new DateTime(2021, 2, 21, 2, 23, 4, 992, DateTimeKind.Local).AddTicks(8050),
                            DemandTime = new DateTime(2021, 2, 21, 2, 23, 4, 996, DateTimeKind.Local).AddTicks(637),
                            IsDeleted = false,
                            Location = "Istanbul",
                            PersonCount = 5,
                            PhoneCount = 10,
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("818dbe25-7ce0-4678-8b0c-f9d737fa3cb1"),
                            CreaatedTime = new DateTime(2021, 2, 21, 2, 23, 4, 996, DateTimeKind.Local).AddTicks(2463),
                            DemandTime = new DateTime(2021, 2, 21, 2, 23, 4, 996, DateTimeKind.Local).AddTicks(2481),
                            IsDeleted = true,
                            Location = "Rize",
                            PersonCount = 3,
                            PhoneCount = 20,
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("2c202633-30ab-4ed3-a0f2-8957cc9ead90"),
                            CreaatedTime = new DateTime(2021, 2, 21, 2, 23, 4, 996, DateTimeKind.Local).AddTicks(2517),
                            DemandTime = new DateTime(2021, 2, 21, 2, 23, 4, 996, DateTimeKind.Local).AddTicks(2519),
                            IsDeleted = true,
                            Location = "Antalya",
                            PersonCount = 25,
                            PhoneCount = 50,
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("107ea30b-d10b-4a1f-8b90-eaba051c7d3b"),
                            CreaatedTime = new DateTime(2021, 2, 21, 2, 23, 4, 996, DateTimeKind.Local).AddTicks(2523),
                            DemandTime = new DateTime(2021, 2, 21, 2, 23, 4, 996, DateTimeKind.Local).AddTicks(2525),
                            IsDeleted = false,
                            Location = "Eskişehir",
                            PersonCount = 35,
                            PhoneCount = 150,
                            Status = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
