// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PhoneBookApp.ReportService.DataAccess.Context.EntityFramework;

namespace PhoneBookApp.ReportService.DataAccess.Migrations
{
    [DbContext(typeof(PhoneBookAppReportContextEF))]
    [Migration("20210217070003_addDemandTime")]
    partial class addDemandTime
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("PhoneBookApp.ReportService.DataAccess.Entities.ReportItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DemandTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<int>("PersonCount")
                        .HasColumnType("integer");

                    b.Property<int>("PhoneCount")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("36cca656-ec46-4a8e-a872-63b01379bbb6"),
                            DemandTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Istanbul",
                            PersonCount = 5,
                            PhoneCount = 10,
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("e02a3bae-2a4c-4a44-bcf1-f734e037a7ca"),
                            DemandTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Rize",
                            PersonCount = 3,
                            PhoneCount = 20,
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("eca0f21d-4cba-4720-9545-26656fa1fe05"),
                            DemandTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Antalya",
                            PersonCount = 25,
                            PhoneCount = 50,
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("99b60188-4903-49e6-8748-42b1bbc921b5"),
                            DemandTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Eskişehir",
                            PersonCount = 35,
                            PhoneCount = 150,
                            Status = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
