// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PhoneBookApp.ReportService.DataAccess.Context.EntityFramework;

namespace PhoneBookApp.ReportService.DataAccess.Migrations
{
    [DbContext(typeof(PhoneBookAppReportContextEF))]
    partial class PhoneBookAppReportContextEFModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("PhoneBookApp.ReportService.DataAccess.Entities.ReportItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<int>("PersonCount")
                        .HasColumnType("integer");

                    b.Property<int>("PhoneCount")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8045f5e4-a5bb-4117-8491-928b3d285ce0"),
                            Location = "Istanbul",
                            PersonCount = 5,
                            PhoneCount = 10,
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("4f955656-c5db-4793-a2bb-0920ac5fb563"),
                            Location = "Rize",
                            PersonCount = 3,
                            PhoneCount = 20,
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("99ec0e66-d598-4819-9a5f-194aed0eb5e8"),
                            Location = "Antalya",
                            PersonCount = 25,
                            PhoneCount = 50,
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("5c31f5e4-ab68-41e0-bbc3-c575059e8918"),
                            Location = "Eskişehir",
                            PersonCount = 35,
                            PhoneCount = 150,
                            Status = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
